version: "3.7"
services:
    mysql_sandbox:
      build:
        context: ./docker/mysql
      container_name: sandbox-db
      working_dir: /app
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: password
      volumes:
        - .:/app
        - ./docker/mysql/init:/docker-entrypoint-initdb.d
        - ./docker/mysql/conf:/etc/my.cnf.d
      ports:
        - "3306:3306"

    apache_sandbox:
      build:
        context: ./docker/apache-php
      container_name: sandbox-apache-php
      working_dir: /app
      volumes:
        - .:/app
      ports:
       - "8080:80"
      tty: true
